freedoom/freedoom

CREDITS

Some fixes to my entry (and my brother's)
(Weird I thought I opened a PR last week but can't find any trace of it. I must have forgot.)

minor CREDITS update

---

musics/d_map01.mus
musics/d_map02.mus
musics/d_map05.mus

musics: Changed 3 tracks in phase 2

---

buildcfg.txt

The title seems a bit too close to the letters.

Slight tweaking to the title

---

lumps/dehacked.lmp
lumps/fdm_deh.lmp

Defines which flat to use as the background during specific intermission texts.
Also cleaned up leftovers.

lumps: adding BGFLATs

---

CREDITS

Should be noted so people know what he did.

Include "D:" for Bradley

---

lumps/textures/textures.cfg

Add missing TNT texture definitions
Re-organize existing TNT/Plutonia definitions
Rename MC1 to P-DBRAN1
Rename MC20 to P-DBRAN4
Fix SLAD11
Add T-SLDRP3 (TNT SLADRIP3)
Add SW{1,2}TSTON (TNT SW{1,2}GSTON)

textures.cfg: Add/reorganize definitions

---

lumps/textures/textures.cfg

textures.cfg: fix AQTRIM05

---

Makefile
scripts/fix-map-names

Add scripts/fix-map-names to fix and test map names. Map names are
tested with make target "test-map-names" and fixed with "fix-map-names".

Add fix-map-names script and build targets

---

manual/manual.adoc

Fix shell icons in the manual

---

Makefile

The rebuild-nodes target needs to be updated from "c" (chapter) to
"e" (episode).

build: Fix the rebuild-nodes target

---

manual/Makefile
manual/manual-es.adoc

Credit goes to CyberSaurus and DoomguyAlighieri on the Freedoom Discord
who translated this in Microsoft .docx format. I think converted it back
into Asciidoc format and added it to the build.
https://discord.com/channels/616148111076884520/857628798921342986/944620737862443019
An example of what the generated manual looks like can be found here: https://soulsphere.org/random/freedoom-manual-es.pdf

Add Spanish translation of manual.

---

graphics/text/create_caption

This is the visible lower left hand corner of the splash screen. I think this is it - I searched for previous years.

Update copyright year to 2022

---

lumps/dehacked/dehacked.txt

Reposting #868 because that was way too many commits.
The current ones have lots of sentence fragments that are somehow austere in tone while still having lots of unnecessary words - a combination that doesn't exactly flow too well. This is an attempt to rewrite a lot of them while trying to keep all the critical elements of each.
A lot of the "it doesn't matter, who cares" / "oh. a trap. AGAIN." talk also felt like it would pull the reader out of the game, however in-character it was clearly intended. (I understand it's inspired by "where's your fat reward and ticket home" from Doom E1 but id was never quite this relentless - if you look at all the other id intermission texts things are much more triumphant and hopeful in tone: D2's "There must be a way to close it on the other side. …

dehacked: rewrite intermission texts.

---

CREDITS

On the Discord guild, [I asked about RMS being in the CREDITS](https://discord.com/channels/616148111076884520/616148111076884524/1103403348968865963) and @fragglet  seemed to be in favour of this idea. So here ya go

RMS no more!

---

lumps/textures/textures.cfg

textures: add patches to M_xDOOR.

---

lumps/textures/textures.cfg

Addresses #995.
PLANET1 is already OK.

textures: make COMPUTE4 256 wide.

---

lumps/textures/textures.cfg

Addresses #1054.
Also removes two redundant lines I'd mistakenly added in #948.

textures: add SPCDOOR0 and STARG4.

---

lumps/textures/textures.cfg

textures: complete AQTRIM03.

---

manual/manual.adoc

I've seen multiple Youtube videos recently that talk about Freedoom as though the "free" part in the name refers to price. It's an understandable misconception but it deserves to be corrected. Let's add a short section to the manual to discuss this.

manual: Add a section about Freedoom's true goal.

---

manual/manual-es.adoc

Fixes #1095.
While we're on it, I'd say the rest of the spanish manual needs a review. I might do that later on.

manual: Spanish translation for goals statements.

---

CREDITS
CREDITS-MUSIC

Thanks to uni for all the legwork in compiling this.
Closes #1074.

credits: list music in separate file.

---

manual/manual-es.adoc

Turns out it's a perfectly functional word for this purpose in Spanish.
The English "device" double entendre, however, is apparently untranslatable. (Please correct me if I am wrong on this.)

manual: use "vanguard" for both languages.

---

graphics/text/Makefile

before:
after (old):
after (new):

graphics: tidy up help screen.

---

graphics/text/Makefile

Also added a reminder to hit Escape to get out of the help screen when I kept pressing F10 while testing.

graphics: add website to help screen.

---

lumps/README.DEMO

demos: correct readme.

---

CREDITS
CREDITS-MUSIC

Quite a few people were never credited in the main text file; also fix a few music credits.

More credits fixes.

---

CREDITS

Credit Hayden49 for E2M2, and credit SUNPYG Senpai for E2M3.

Add more uncredited people.

---

CREDITS-MUSIC

https://www.doomworld.com/forum/post/2756145

Title jupiter_ex's tracks

---

Makefile
NEWS.adoc
dist/io.github.freedoom.FreeDM.metainfo.xml
dist/io.github.freedoom.Phase1.metainfo.xml
dist/io.github.freedoom.Phase2.metainfo.xml
scripts/news-to-feed

This includes all places that the version appears as well as a new "NEWS" section with the new changes.
--
This is a work in progress. I'll update as we talk about how to summarize what happened in #development. The website will probably have to be updated at the same time as well.

Bump version to 0.13.0

---

CREDITS-MUSIC

Welp, fuck. I didn't notice this before release...
(btw @mc776, check [LT1 issue 1](https://codeberg.org/mc776/LibTech1/issues/1))

Music credit fixes

---

.gitignore
CREDITS
CREDITS-LEVELS
CREDITS-MUSIC
Makefile

(hopefully) Closes #1325.
@selliott512

Address #1325 with a CREDITS-LEVELS file.

---

CREDITS-LEVELS
lumps/dehacked/dehacked.txt

levels: rename Episode 2.

---

dist/io.github.freedoom.FreeDM.desktop
dist/io.github.freedoom.Phase1.desktop
dist/io.github.freedoom.Phase2.desktop

dist: add Spanish to desktop files.

---

CREDITS-LEVELS

Dunno why I didn't do this in the initial PR...

Add a "previously featured in 0.12.1" section to CREDITS-LEVELS

---

CREDITS-LEVELS

These were symlinked under the wrong authors (mainly just very small fixes), _**why???**_
I'm honestly confused how none of this was organized when the project was conceived...

Fix a few map authors

---

CREDITS-MUSIC

[Old log from 2001](https://github.com/freedoom/historic/blob/trunk/0.6.4/ChangeLog#L1225) had this track's title.
~~brain go happy mode when people log things :333~~

Fix Vicious' old DM17 title

---

lumps/dehacked/dehacked.txt

Closes #897.
Only tested in Chocolate but I really can't see any reason why the behaviour would break in Crispy or dsda-doom or anything else.

dehacked: make minigunner and SS call A_PosAttack.

---

lumps/p1_uminf.lmp
lumps/p2_uminf.lmp

lumps: umapinfo fixes

---

CREDITS

credits: update nrkn's info.
