freedoom/freedoom

graphics/titlepic/create_caption
Do not FTBFS if the user does not have ghostscript / gsfonts installed.
Instead try some other fonts commonly installed by Linux distributions.
The patch is written to be easily extendable with extra font names, but
to be independent of the order of "convert -list font" output. Each
listed font is searched for in turn, and the first one found is used.
=> titlepic/create_caption: try alternative fonts

Makefile
Hi,
This tiny tweak is needed to make the build reproducible.
Appart from having high packaging standards; having reproducible
build also sometimes help to identify some weird/old bugs;
and here that doesn't hurt either in anyway.
https://wiki.debian.org/ReproducibleBuilds/TimestampsInDocumentationGeneratedByAsciidoc
=> make the build reproducible

graphics/text/Makefile, graphics/text/config.py, graphics/titlepic/Makefile, graphics/titlepic/create_caption
Rather than using the bland fonts for the titlepic, instead generate 
images using Freedoom's font and textgen. These images get overlayed
where the "Phase 1" and "Phase 2" white-lettered words used to be.
Also, replace the website URL on the titlepic with a copyright notice,
as the website URL is already mentioned on the help screen (where
it should be). And removed the "Version: " part of the version footer
text because it's not necessary. Finally, make footer text orange 
because it stands out well in a nice way :)
Preview: http://imgur.com/a/9PtzQ
=> titlepic: use image instead of text, change footer

lumps/textures/textures.cfg
Set DBRAIN1's size to 64x32, and remove MC patches from it.
This should address the issues brought to attention in #406 and [this thread on Doomworld](https://www.doomworld.com/forum/topic/93689-the-lava-flow-texture-is-bugged/).
Plutonia compatibility can be achieved by creating a separate PWAD with Plutonia's texture definitions. This is why the MC and AROCK animations work when playing Freedoom with Plutonia 2 or PRCP. Plutonia 2 and PRCP both include the Plutonia texture definitions, in addition to a few new ones.
=> textures.cfg: fix DBRAIN animation.

.gitignore, Makefile
This is an updated and significantly changed attempt to integrate wad2image into the Freedoom build. Some highlights since the last pull request I submitted (#432):
- Moved most functionality into wad2image. For example, my previous pull request added scripts to the "scripts" directory. The new approach is for wad2image to be copied to or symlinked to the "scripts" directory, but otherwise there are no new scripts.
- In addition to animated GIFs and the black or white images seen in my [Freedoom forum post](https://www.doomworld.com/forum/topic/93601-ive-created-a-utility-that-displays-differences-in-wad-revisions-visually/) color coded difference images can be generated on top of reduced color saturation images. I've added an example to [wad2image's home …
=> Added targets, variables and help for wad2image integration.

Makefile
Unfortunately for the previous pull request (#480)  the logic to find the top level directory for wad2image did not work as well as I hoped. It's particularly a problem for the `wad-image-diff` targets where the `git-wad-diff.sh` script is used as that bash script is not as sophisticated as `wad2image.py` for finding the top level directory. To address this I just created a new version of wad2image (version 0.9.5) that has a new command line option `--get-top-dir` so that `git-wad-diff.sh` can benefit from that logic.
The small fix to `Makefile` is to use the top level directory that `wad2image.py` says rather than attempting to calculate it based on the path.
I've made sure all of the examples shown by `wad-image-help` work for the following:
- wad2image is symlinked to the `scripts` …
=> Improved wad2image top level directory determination.

lumps/textures/Makefile, lumps/textures/build-textures
A useful vanilla-compatible trick is that it's possible to include
sprites as patches inside texture definitions. It turns out that
both Final Doom IWADs added textures which do this, and Freedoom
inherits this as a result. We shouldn't include these sprites in the
pnames.txt that gets generated for inclusion in wadinfo.txt, since
they're already defined in wadinfo.txt under [sprites] and won't
be found under patches/ anyway.
This should help as a step towards resolving #485.
=> textures: Don't include sprites in pnames list.

lumps/dehacked.lmp
The firing frames for the zombie and assault tripod look weird if they're not 
shown in full brightness, so add a dehacked tweak to set them to full
brightness. Doom has the same bug but it isn't quite as noticeable.
This could theoretically cause a mod compatibility issue since unexpected
frames might be fully lit. However, (1) the worst that can happen is a minor
cosmetic issue, and (2) I don't know of any actual mods this affects (maybe
there aren't any). I think the benefit outweighs the potential downside.
=> dehacked: Turn on full brightness for a few frames

dist/freedm.appdata.xml, dist/freedoom1.appdata.xml, dist/freedoom2.appdata.xml
Those tags are now required by Flathub.
This closes #522.
=> dist: Add releases and content rating to AppStream metadata

lumps/dehacked.lmp
I still hate that "...", but I'm starting to think the aggravation is not really that itself but the use of a direct quote for "you" the player for something they never actually said.
So looking at the E4 text again to see how it could be avoided, I noticed a bunch of other little weird things... the past tense on the first sentence clashing with the rest of the present tense; the "despite" doesn't really fit with the logical progression; and while I know exactly what "plump down" was intended to convey it seems a bit nonstandard. It's also missing punctuation at the end, in contrast with the other intermission texts.
I've also modified C5 and C6 for similar reasons.
=>  More intermission text adjustments 

graphics/text/config.py, manual/manual.adoc
Extreme Carnage should have a period to be consistent with the other skills. Yes, I know the previous labels are full sentences, but given we all know the final skill must end with a ! it does end up being left as the only unpunctuated one.
I'm starting to dislike "INSANITY!" for multiple reasons, but it also seems kinda flat and uninspired after decades of eXtReMe / "totally random crazy monkey spork uwu" whatever in popular culture.
"Mayhem" might be a better descriptor anyway for the additional speed and damage and randomly respawning monsters.
=> Fixes to the skill levels

dist/freedoom
Engines such as Odamex may not have a default search path and simply
search for freedoom1.wad relative to the current directory. This can
cause an unexpected WAD file not found error when executing the freedoom
script.
This issue is mitigated by setting a default DOOMWADPATH environment
variable with sensible search paths, if it is not already set. All
engines listed in the PORTS variable support the DOOMWADPATH environment
variable, which makes it a simple and convenient way of helping prevent
this error.
=> dist/freedoom: Set DOOMWADPATH with sensible default value if unset

lumps/textures/textures.cfg
Weirdly there's a STARBR2 but no STARBR1, and there are also these
SW11_4 and SW11_5 patches which are not used in anything except for
in COMPUTE3 as part of a montage texture. It seems like a natural fit.
=> textures: Add a STARBR1 texture.

buildcfg.txt
This was only ever used for build of the "shareware" WAD and has not
been relevant for a long time now.
=> buildcfg: Get rid of PHASE1_OR_PHASE2 #define.

Makefile
This makes the "command: command not found" error no longer occur on
systems where the default shell is not `bash`, or does not support the
`bash` builtins. Additionally, a sane environment is set for safer
shell command use and scripting.
The environment settings for `bash` here do the following:
- Terminate on errors, including signal `ERR` traps. (-e, -E)
- Ensure that shell variables are set before use. (-u)
- Print the shell command, and arguments, as they're run. (-x)
- Fail on errors in any command in a pipeline. (-o pipefail)
=> Makefile: Explicitly define the shell (bash) and its env.

Makefile
Check if deutex supports PNG based on its help output and fail the
build early if not.
=> Makefile: Warn if deutex does not support PNG

manual/manual.adoc
[Link to viewable Adoc
](https://github.com/mkrupczak3/freedoom/blob/master/manual/manual.adoc)
Changes:
* Add a "contributing" section which explains how Freedoom is free and open source (free as in free beer and free as in free speech), and provides links to the project's GitHub page, the Doomworld forums, the Freedoom discord, and the help articles on GitHub for how to get started working with git
* Add a tactical tip for using the angle grinder to take care of flesh worms and Trilobites
Tactical Tip:
If you encounter a horde of flesh worms or stealth worms, The angle grinder is a great weapon to use both to conserve ammo and avoid taking damage. Worms can’t attack while being sawed, and if you back into any corner that is roughly as wide as or narrower than a right angle, they can …
=> Update manual with "Contributing to Freedoom" section and a 'tactical tip' for the angle grinder

.github/workflows/make.yml
Uses Github Actions to run `make` and upload the build artifacts
=> Add Continuous Integration

dist/io.github.freedoom.FreeDM.desktop, dist/io.github.freedoom.Phase1.desktop, dist/io.github.freedoom.Phase2.desktop
See <https://www.hadess.net/2020/05/dual-gpu-support-launch-on-discrete-gpu.html> for more information about this newly added `.desktop` entry property.
=> dist: Request dedicated GPU when starting Freedoom from `.desktop` file

buildcfg.txt
Sorry, I should've noticed this long before https://github.com/freedoom/freedoom/pull/699 was finalized.
This one sprite is 3 pixels too far to the left compared to the 2 sprites around it.
=> SPOST0: fix X alignment.

manual/Makefile, manual/manual-es.adoc, manual/manual.adoc
This seems like a better choice for the manual since it is a "booklet"
size similar to the original Doom manual, rather than a "full page"
size that is rather unusual for a book.
Several changes are needed to allow asciidoctor to successfully produce
a PDF. The main change is to set a bunch of images to 100% width,
especially in tables where this means "100% of cell width". This allows
the tables to scale down successfully to the smaller size. I have also
adjusted the column widths of various tables to accommodate the smaller
size without the text wrapping awkwardly.
=> Change manual to build as A5 paper size.

BUILD-SYSTEM.adoc, CREDITS, README.adoc
Also, update README.adoc to encourage people to set the author of commits correctly when creating commits on behalf of others.
---
I thought I'd limit the search to just since the last release.
For the work done (for `D`) I just used top level files or directories modified. For example, here's what Korp modified since v0.12.1:
```
a=Korp; git log --no-merges v0.12.1..origin/master --format=format: --name-only --author $a | sed 's|/.*$||g' | sort -u | grep -v '^$'  | tr \\012 , | sed 's|,$||g; s|,|, |g'; echo
buildcfg.txt, musics, patches, sprites
```
I attempted to merge what I found with any existing entries.
Fraggle, I updated your email address from `idgames@soulsphere.org` to `fraggle@soulsphere.org` based on your recent commits.
=> CREDITS: Add contributors since v0.12.1

CREDITS
For users added by selliott512 update the "D" lines so that they include changes prior to 2017.
---
It's possible that there are still users that were missed because their name does not appear in `git log` as an author. Feel free to let me know about them, or mention them in #development.
=> CREDITS: Add older "D" changes for new users

CREDITS
Add contributors since the last major update of CREDITS at the end of 2022.
---
This is based on the recent discussion in #development.
=> CREDITS: Add contributors since 2022

lumps/textures/textures.cfg
A lot of IRL chainlink fences aren't nearly as tall as the full-height 128-unit texture we have now. An extra fence texture can be useful when creating more realistic environments.
(Disclosure of interest: yes the new back alley in Map16 is bugged in vanilla right now. I've got a fix lined up that sets that fence to extend the full 128 units off the ground but if this gets merged first I intend to go back and fix it the right way.)
=> textures: add smaller MIDSPACE.

.github/workflows/make.yml
This script currently throws these warnings:
Reading the relevant blog posts, I can see that the CI will just end up being completely broken by June, and this PR is meant to prevent that from happening.
It makes the following changes:
- Switch from `actions/checkout@v2` to `actions/checkout@v3`. There are no real changes in how the action itself is used (at least none relevant to our use case), so it's a simple version bump.
- Changes the `::set-output` command to use Environment Files instead. Other than how the command itself is written, there are no changes to its use, so it amounts to just a small change in syntax.
=> Update GitHub Actions "make" script

CREDITS
> Changed copyright year
I think it's kind of silly that we need to remember to keep on updating the copyright year every time the real-life year changes, so I think this would be easier, although I'm not going to die on this hill if this part gets rejected
> Added myself to the credits
I have not done work _for_ freedoom/freedoom, [but I have done stuff for the website](https://github.com/freedoom/freedoom.github.io/commits?author=DynTylluan), so giving me credit would be nice
Cheers
=> Changed copyright year plus added myself to the credits

CREDITS
GojiBerry should be credited for "sound" not "levels". Also, the "=======" at the end is almost certainly left over from a previous git merge conflict - it has exactly the seven characters expected. I kept it until now thinking it had some meaning to something, but that's unlikely.
=> CREDITS: Update GojiBerry, remove merge remnants

scripts/fix-gfx-offsets
The fix-gfx-offsets script incorrectly used unsigned integers (I) when interpreting grAb chunks, which resulted strange large values that are close to 2^32 in buildcfg.txt. The fix is to use signed integers (i).
---
This two character fix prevents strange and clearly wrong values in `buildcfg.txt`. For example, consider this hunk from the `buildcfg.txt` diff produces by running `make fix-gfx-offsets`:
```
@@ -2213,8 +2213,8 @@ PISFA0 -147 -66
PISGA0 -138 -104
PISGB0 -138 -83
PISGC0 -139 -88
-PISGD0 -140 -87
-PISGE0 -141 -90
+PISGD0 4294967156 4294967209
+PISGE0 4294967155 4294967206
PISTA0 10 14
PLAYA1 18 54
PLAYA2A8 11 54
```
Each of the four large values is 2^32 added to the corresponding negative value seen above it. For example:
```
4294967156 = 4294967296 -140
```
where 4294967296 = …
=> scripts: Signed ints for grAb in fix-gfx-offsets

Makefile, scripts/fix-deutex-pngs, scripts/map-color-index
Add scripts:
fix-deutex-pngs - Apply the output of deutex to the build
map-color-index - Map from one color index to another
Script fix-deutex-pngs is to standardize PNGs by applying the result of the expanding IWADs produced with deutex to the build. It is invoked by build target fix-deutex-pngs
Script map-color-index can map from one color index to another. Most likely it will be used to map form legacy transparency 255 to similar color 133, which can be done by build target
fix-legacy-transparency-pngs.
---
Here's my attempt at fixing the D2TWID / color 255 transparency issue.
This MR adds make targets and scripts that help with, but does not itself, do the following things:
1. Standardize the PNGs by extracting them from deutex (`fix-deutex-pngs` make target).
2. Map color 255 to 133 …
=> build: Add fix-pngs make target and scripts

manual/manual-es.adoc, manual/manual.adoc
commit 89f918f5173b7 last year changed the manual to build as an A5 booklet. However, some of the tables now look very compressed with the smaller page width. We can make things look a lot nicer by reducing the number of columns:
* Weapons table: sprite column is eliminated (sprite is kept, but moved to the name column), and ammo column (moved to description column). This is a reduction from five columns to three in total.
* Special items table: name and description columns are merged. This is a reduction from three columns to two.
* Monsters table: name and description columns are merged. This is a reduction from three columns to two.
=> manual: Reduce number of table columns.

graphics/text/create_caption
To support Python PIL 10.0.0 this change uses newer API textbbox() when available, and older API textsize() when not.
---
I've tested this using a static version in `Makefile` (the version otherwise causes the PNGs produces to be different):
```
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
-VERSION=$(shell git describe --abbrev=8 --dirty 2>/dev/null || echo v0.12.1)
+VERSION=static-version
```
and found that it produces exactly the same `graphics/fd*title.png` PNGs for PIL 7.2.0 and 10.0.0 with this change, which again match the PNGs produces for 7.2.0 without this change.
=> create_caption: Python PIL 10.0.0 support

Makefile, scripts/news-to-feed
Rather than maintaining feed.xml on the website manually the news-to-feed script, added by this commit, will generate it based on NEWS.adoc in this repository.
Also, make target news-to-feed has been added to run the script.
---
I don't know that we need this, but I wrote it, and it may be handy. It should be safe (especially if we don't use it). Merge if you want. 
See the conversation starting 2023-07-29 in #develop on Discord.
=> scripts: Add news-to-feed script

manual/Makefile, manual/manual-es.adoc, manual/manual.adoc
Some of the table columns were not large enough to fit the text, or the words themselves were too big when smaller words would have done.
Lots of single-word lines at the ends of paragraphs.
Removed a bit of redundant information.
Vital links in the submitting/visiting sections needed to have visible URLs in case one really did print them out.
Added a copy of the BSD licence and a link to the website.
Zip of built PDFs in English and Spanish showing before and after:
[man.zip](https://github.com/freedoom/freedoom/files/13447785/man.zip)
Controls table now unjanked (EDIT: the unspaced slash line spillovers in Spanish are also fixed, just too lazy to update the screenshot)
Menu items, keyboard shortcuts, cheats all now on one page
Enemies section more compact
Front page more …
=> manual: optimize for PDF formatting.

manual/manual-fr.adoc, manual/manual.adoc
asciidoctor-pdf outputs a warning when ordered lists are numbered entirely with "1.". It wants actual consecutive integers. Prior to this fix there were 14 warnings such as:
asciidoctor: WARNING: manual.adoc: line 234: list item index: expected 2, got 1
in the English and French manual. Interestingly it amkes no difference in the PDF produced, but let's minimize the number of warnings in the build.
----
I know we talked about this, mc776. I'm hoping you don't object on principle (the principle being that asciidoctor-pdf shouldn't have such a warning because it makes lists harder to maintain, like you said) since it adds 28 warnings to `make dist` and `make install`. And there's something to be said for being explicit as well.
=> manual: Fix warning in tutorial steps 1-15

.gitignore, Makefile
Fix those places where "CREDITS-MUSIC" did not have the same processing as "CREDITS".
---
This means that `make dist` and `make install` will now include `CREDITS-MUSIC` where they had previously included only `CREDITS`.
=> build: Add processing for "CREDITS-MUSIC"

lumps/dehacked/dehacked.txt
The DeHackEd text for the MAP31 to 32 secret exit still mentions "Safety in Numbers" - 0.10 and before's MAP31.
> hell-rock that strange prison had been on.
This could most likely be worded better.
=> Remove reference to old MAP31 in DeHackEd

NEWS.adoc
Unfortunately I overlooked adding this wonderful new monster to NEWS.adoc for 0.13.0.
---
The downloadable ZIP files have already been tagged, so I don't think we should mess with them, but there's no reason that `NEWS.adoc` can't be retroactively made accurate in `master` for previous releases.
I can update the website with this change once it's merged.
=> NEWS: Add octaminator to NEWS.adoc

dist/io.github.freedoom.FreeDM.metainfo.xml, dist/io.github.freedoom.Phase1.metainfo.xml, dist/io.github.freedoom.Phase2.metainfo.xml
These should now be "forever" URLs linking to image files that can be overwritten with each release without touching these XML files each time.
The current website organizes everything so that we have 8 screenshots of each game, numbered 1-4 for Chocolate and 5-8 for GZ. Including screenshots 1, 2, 7 and 8 therefore should give us a fairly representative variety.
If it's better to link to the full-size screenshots instead, or if different screenshot number should be used for future maintainability, please let me know.
=> dist: update screenshots on metainfo XML files.

CREDITS
Keeping the 19 in case someone does only a string search for "mortrixs19" and not "mortrixs".
Got rid of the time stamp in the invitation to update info.
=> credits: remove doubled Mort.

scripts/makepkgs
The "is" keyword is no longer supported, which result in a warning in "make dist" as well as unintentionally having a "v" in the resulting ZIP files and directory within those ZIP files.
---
This solves an 11th hours 0.13.0 mystery I had with my ZIP files looking different than previous ones - "is" support depends on the Python version whereas this  fix does not.
This should be backported to 0.13.1. Should we have a "backport" tag?
=> scripts: For "makepkgs" replace "is" with "=="

dist/io.github.freedoom.FreeDM.metainfo.xml, dist/io.github.freedoom.Phase1.metainfo.xml, dist/io.github.freedoom.Phase2.metainfo.xml
Switch to using the full screenshots in the metainfo files. These URLs should not change.
----
I've checked them, and I've added a comment that should help with the confusion as a result of their being both PNGs and JPGs. My impression is these should be pulled infrequently such as when flatpak and Linux repo packaging is done each Freedoom release, or Linux distro release.
=> dist: Use non-thumbnails for screenshots.

README.adoc
This is left over from before the change to vanilla as the target for levels. The change should inherently ensure that scenes will never be too complicated.
=> README: Remove outdated paragraph

.github/workflows/make.yml
Version 1 is deprecated and now fails when run:
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
=> CI: Bump to upload-artifact v4.

manual/freedoom-manual-es.adoc
Addresses #1370.
I've removed a page break between the installing and menus section since the fix causes one line from the former to spill over onto a new page.
=> manual: fix Spanish translation errors.

lumps/fdmuminf.lmp
Perhaps a Python integration to autofill the `UMAPINFO` at build-time will be needed, _if_ the issue persists, as seen in /issues/1455.
=> Udpate missing FDM names in UMAP

lumps/fdmuminf.lmp, lumps/p1_uminf.lmp, lumps/p2_uminf.lmp
Not only is this field part of the `UMAPINFO` specification standard, ports such as Woof and KEX are capable of displaying the `author` of the map for the payer either as a "level announcement" or a log function in the console.
=> Add authors to umapinfo lumps

lumps/p1_uminf.lmp
=> Fix typo in Phase 1 `UMAPINFO`

graphics/text/Makefile, graphics/text/help.txt
This fixes #1489, where the keys were being obscured by the menu skull that is drawn on the help screen by vanilla Doom. Rather than just shuffle around the contents of the help screen, I opted to simplify it by removing a lot of the clutter.
The old help screen was created before the Freedoom manual was added, so there's no need for us to include every in-game item. Instead, we can delegate to the manual by including a link to it, and cut things back to just a small selection of example items.
=> Simplify the help screen

.github/workflows/make.yml
There's no need for us to recompile deutex every time we build Freedoom, since it's already in Github Actions. In a comment on #671 it was mentioned that this was done to work around a crash in the version of deutex in bionic, but that bug is long-fixed now.
=> CI: Use the version of deutex from GHA Ubuntu

README.adoc
This does some major rewording to the README file, particularly the introduction section, to emphasize that Freedoom is its own game and not a clone of Doom.
This change is prompted by a couple of things: firstly [a Doomworld thread](https://www.doomworld.com/forum/topic/153626-freedoom-looks-sounds-cheap/) from a couple of weeks ago where I had to state this again, and secondly my discovery today that a page on the Doom Wiki lists Freedoom as one of several "clones" of other games.
We need to work harder at dispelling this idea and even in our README file we weren't doing a good enough job.
=> README: Rewording to emphasize the project's independence
